# Generated by Django 4.2 on 2023-06-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneStore', '0002_remove_phone_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
