# Generated by Django 4.2 on 2023-06-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneStore', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=2)),
                ('item', models.ManyToManyField(related_name='item', to='PhoneStore.phone')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
