# Generated by Django 4.2 on 2023-06-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneStore', '0004_myuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
