# Generated by Django 4.2 on 2023-06-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneStore', '0005_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
