# Generated by Django 4.2 on 2023-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneStore', '0005_remove_myuser_cart_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='PhoneStore.phone'),
        ),
    ]
