# Generated by Django 4.2 on 2023-06-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneStore', '0006_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uqsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamqe', models.CharField(max_length=100)),
                ('passwqord', models.CharField(max_length=100)),
                ('emaqil', models.EmailField(max_length=100)),
            ],
        ),
    ]
